# Generated by Django 5.1.4 on 2024-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x200?text=No+Image', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='message',
            field=models.TextField(default='A delicious recipe!'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_to_make',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='New Recipe', max_length=200),
        ),
    ]
